### ISSUE TITLE
Another problem with encoding ... this time it is None

### ISSUE THREAD

**Issue by mcepl** [HairySpoon/htlfc#4]
[BostonHerald.com_-_News_&_Opinion.zip](https://github.com/HairySpoon/htlfc/files/10397787/BostonHerald.com_-_News_._Opinion.zip)

```
stitny/tmp$ htlfc BostonHerald.com_-_News_\&_Opinion.maff
Traceback (most recent call last):
  File "/home/matej/.bin/htlfc", line 8, in <module>
    sys.exit(run_htlfc())
  File "/home/matej/.local/lib/python3.10/site-packages/htlfc/__init__.py", line 6, in run_htlfc
    main.main()
  File "/home/matej/.local/lib/python3.10/site-packages/htlfc/main.py", line 125, in main
    target = convert.convert(source) # conversion
  File "/home/matej/.local/lib/python3.10/site-packages/htlfc/merger/convert.py", line 38, in convert
    content.merge_iframes()
  File "/home/matej/.local/lib/python3.10/site-packages/htlfc/merger/xmltree.py", line 227, in merge_iframes
    frame_text1 = frame_text1.decode(encoding1)
TypeError: decode() argument 'encoding' must be str, not None
stitny/tmp$ 
```

**Comment by HairySpoon** [comment]
Thanks for reporting this.

**Comment by HairySpoon** [comment]
A solution has been released on PyPi. Please upgrade to V0.3.1, evaluate and report.

**Comment by mcepl** [comment]
Perfect. Thank you.

**Comment by mcepl** [comment]
Another one (originally `.war`):

[povidani-s-Rogerem-20060520_maff.zip](https://github.com/HairySpoon/htlfc/files/10413906/povidani-s-Rogerem-20060520_maff.zip)
[povidani-s-Rogerem-20060520_war.zip](https://github.com/HairySpoon/htlfc/files/10413907/povidani-s-Rogerem-20060520_war.zip)

**Comment by HairySpoon** [comment]
Both objects contain empty .css files. This can be observed with the --pause option or simply unzipping them. An update is on its way that will catch this error (and issue #2 as well) and print a short diagnostic instead of error dump. 

By the way, your files can be visualised with the --browser option, but not converted.

**Comment by HairySpoon** [comment]
Take a look at version 0.3.2. It won't convert your files, but the error message should be more informative.

**Comment by mcepl** [comment]
> Both objects contain empty .css files. This can be observed with the --pause option or simply unzipping them. An update is on its way that will catch this error (and issue #2 as well) and print a short diagnostic instead of error dump.

Hmm, I would actually think that this should be just a warning. Of course, the user should know the conversion was not perfect, but otherwise it should proceed as well as it could (either inserting empty style-sheet or nothing at all). When converting a page from year 2006 (which is this case), there is most likely no chance to getting back to the original web page and re-download (that, I would argue, is whole point of web archives), so salvaging of whatever we have seems like the best option.

BTW, do not consider this ticket to be a criticism of your work too much. It faithfully converted couple of hundred of web archives on my drive for which I am very thankful.

> By the way, your files can be visualised with the --browser option, but not converted.

Yes, but the conversion (and including all external resources into the page) is the most valuable part of your script. Technically, I can visualise the archive just by `unzip`.

**Comment by HairySpoon** [comment]
You make a good point. Will implement warnings but allow me some time - perhaps a week.

Yesterday I looked at reporting empty files (not just css) and concluded that it's not as easy as catching exceptions because the conversion needs to keep running whilst processing error messages.

**Comment by HairySpoon** [comment]
Please test your files with latest release, version 0.4.0

**Comment by mcepl** [comment]
```
stitny/tmp$ htlfc povidani-s-Rogerem-20060520.maff
Traceback (most recent call last):
  File "/home/matej/.bin/htlfc", line 8, in <module>
    sys.exit(run_htlfc())
  File "/home/matej/.local/lib/python3.10/site-packages/htlfc/__init__.py", line 6, in run_htlfc
    main.main()
  File "/home/matej/.local/lib/python3.10/site-packages/htlfc/main.py", line 129, in main
    (target,warnings) = convert.convert(source) # conversion
  File "/home/matej/.local/lib/python3.10/site-packages/htlfc/merger/convert.py", line 26, in convert
    content.add_info_bar(source.metadata)
  File "/home/matej/.local/lib/python3.10/site-packages/htlfc/merger/xmltree.py", line 87, in add_info_bar
    with importlib.resources.open_text("merger", "infobar.css") as fp:
  File "/usr/lib64/python3.10/importlib/resources.py", line 82, in open_text
    open_binary(package, resource), encoding=encoding, errors=errors
  File "/usr/lib64/python3.10/importlib/resources.py", line 43, in open_binary
    package = _common.get_package(package)
  File "/usr/lib64/python3.10/importlib/_common.py", line 66, in get_package
    resolved = resolve(package)
  File "/usr/lib64/python3.10/importlib/_common.py", line 57, in resolve
    return cand if isinstance(cand, types.ModuleType) else importlib.import_module(cand)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'merger'
stitny/tmp$ 
```

Which merger it is? https://pypi.org/project/merger/ ?

**Comment by mcepl** [comment]
Yes, that works now. Thank you.
